import { Timestamp } from "firebase/firestore";

const UNSPLASH_IDS = [
  "hVqL2OpIISg", "WOvpvR62dNQ", "P7o-1UnFaqw", "U2Xp9QExkSQ", "RuCUa6CtfFE",
  "vLIeyl_ml8s", "0wNGC8KuHUU", "BxFfhW4I-lg", "x5LH4df5cCk", "H988EpA-27A",
  "mPgNho2PJ60", "Fjqt6RmYkx4", "x4-h2jJrDPg", "dd-ob8uFxb8", "3OUdX61uPH4",
  "zrJbb0GaN0g", "re1oHeWEPjI", "dvHFa8FJ9RY", "rW0X4xa_hpw", "NnD1jMzybbE",
  "3yvcSV_8ZlQ", "WqYxPyLXU78", "PARIuwa_Ssc", "zSgMdzZg7V0", "J24bvenUTD0",
  "wewzzx11ShI", "L80cC_5nAFI", "6T4Z_YqOXyg", "m4dagsplsKA", "qoGdi3R3ekQ",
  "F_VqA-n3EYo", "HQgfLYqIkBA", "ygK61Go4MUU", "rwb35vZTpBo", "v5V99uy_Qus",
  "QgK0yj6kc6k", "zeQaRmQf4Jk", "12N9XSSuygc", "GX-yJKiY-JA", "K5oh_cDnUW8",
  "QkZgJ7jWzIs", "zz6-LqiW4mY", "8angSQtYgKc", "lwjBhbslaF4", "u1DhoJNcmqM",
  "glCYj9K1VpU", "ZP7HXfjRVcY", "i8lhklBB-CY", "DJD07KW_c_Q", "dzA9vh4jGFE",
  "HUxzAuYDQaI", "o73uo9l6Xxg", "kKAb6gkBnrw", "kFu6tHmX-fw", "DR9y0E7ehVM",
  "LE-AhR64pJA", "dXfhXa49gnU", "47uULlB3rrE", "xu_zM4np434", "KWnSpfql_4g",
  "_45j01M-wRI",
];

let imageIndex = 0;
function imgUrl(): string {
  const id = UNSPLASH_IDS[imageIndex % UNSPLASH_IDS.length];
  imageIndex++;
  return `https://images.unsplash.com/photo-${id}?w=400&h=400&fit=crop&auto=format`;
}

function pick<T>(arr: T[]): T { return arr[Math.floor(Math.random() * arr.length)]; }
function randInt(min: number, max: number): number { return Math.floor(Math.random() * (max - min + 1)) + min; }

interface DummyProduct {
  name: string;
  description: string;
  design: string;
  categoryId: string;
  images: string[];
  videoUrl: string;
  price: number;
  originalPrice?: number;
  badge: string;
  costPrice: number;
  weight: number;
  metalType: string;
  stoneType: string;
  stoneWeight: number;
  makingCharge: number;
  warranty: string;
  sku: string;
  quantityInStock: number;
  isActive: boolean;
  isFeatured: boolean;
  brand: string;
  modelNo: string;
  baseMaterial: string;
  plating: string;
  color: string;
  productType: string;
  idealFor: string;
  netQuantity: number;
  occasion: string;
  createdAt: unknown;
  updatedAt: unknown;
}

const products: Omit<DummyProduct, "categoryId">[] = [
  {
    name: "Vivanta Alloy Gold-plated Multicolor Jewel Set",
    description: "Elegant 5-piece jewelry set featuring a stunning necklace, matching earrings, maang tikka, and bracelets. Crafted from high-quality alloy with a radiant gold-plated finish and multicolor stone embellishments. Perfect for weddings and festive occasions.",
    design: "DS-2401", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 153, originalPrice: 899, badge: "offer", costPrice: 76,
    weight: 45.2, metalType: "Gold", stoneType: "Cubic Zirconia", stoneWeight: 2.5,
    makingCharge: 50, warranty: "6 months", sku: "SKU-VIV-001", quantityInStock: 25,
    isActive: true, isFeatured: true, brand: "Vivanta", modelNo: "MOD-VIV-2401",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Multicolor",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 5, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "TONOLIKA JEWELLERY Brass Gold-plated Gold Jewel Set",
    description: "Traditional gold jewelry set made from premium brass with high-quality gold plating. Includes a heavy necklace, drop earrings, and a matching bracelet. Intricate floral pattern with filigree work.",
    design: "DS-2402", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 118, originalPrice: 999, badge: "offer", costPrice: 59,
    weight: 52.8, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 30, warranty: "3 months", sku: "SKU-TON-002", quantityInStock: 40,
    isActive: true, isFeatured: false, brand: "TONOLIKA JEWELLERY", modelNo: "MOD-TON-2402",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "TAGADO Brass Gold Jewel Set with Kundan Work",
    description: "Beautiful kundan-style jewelry set crafted from polished brass with a luxurious gold finish. Features traditional peacock-inspired design with hanging elements. Lightweight and comfortable for all-day wear at weddings.",
    design: "DS-2403", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 89, originalPrice: 830, badge: "offer", costPrice: 44,
    weight: 38.5, metalType: "Gold", stoneType: "Cubic Zirconia", stoneWeight: 3.0,
    makingCharge: 25, warranty: "No warranty", sku: "SKU-TAG-003", quantityInStock: 15,
    isActive: true, isFeatured: false, brand: "TAGADO", modelNo: "MOD-TAG-2403",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "RIENTA JWL Alloy Gold-plated Gold Mangalsutra Set",
    description: "Modern mangalsutra-style jewelry set made from durable alloy with elegant gold plating. Features a beautiful pendant with black bead accents and matching earrings. Ideal for daily wear and special occasions.",
    design: "DS-2404", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 188, originalPrice: 999, badge: "offer", costPrice: 94,
    weight: 28.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 40, warranty: "6 months", sku: "SKU-RIE-004", quantityInStock: 30,
    isActive: true, isFeatured: true, brand: "RIENTA JWL", modelNo: "MOD-RIE-2404",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Gold",
    productType: "Mangalsutra Set", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "J B JEWELLS Alloy Multicolor Fashion Necklace & Earring Set",
    description: "Trendy fashion jewelry set with vibrant multicolor stones arranged in an intricate pattern. The necklace features a layered design with a central pendant. Matching earrings complete this stunning ensemble.",
    design: "DS-2405", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 222, originalPrice: 999, badge: "price_dropped", costPrice: 111,
    weight: 35.6, metalType: "Silver", stoneType: "Cubic Zirconia", stoneWeight: 4.0,
    makingCharge: 60, warranty: "1 year", sku: "SKU-JB-005", quantityInStock: 20,
    isActive: true, isFeatured: false, brand: "J B JEWELLS", modelNo: "MOD-JB-2405",
    baseMaterial: "Alloy", plating: "Silver-plated", color: "Multicolor",
    productType: "Necklace", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "OChori Brass Gold-plated Antique Gold Jewel Set",
    description: "Antique-finish jewelry set with a vintage charm. Made from durable brass with rich gold plating. The set includes a heavy necklace, earrings, and a maang tikka with traditional Indian motifs.",
    design: "DS-2406", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 178, originalPrice: 1699, badge: "offer", costPrice: 89,
    weight: 48.2, metalType: "Gold", stoneType: "Ruby", stoneWeight: 2.0,
    makingCharge: 45, warranty: "6 months", sku: "SKU-OCH-006", quantityInStock: 18,
    isActive: true, isFeatured: true, brand: "OChori", modelNo: "MOD-OCH-2406",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "brado jewellery Brass Gold-plated White Pearl Jewel Set",
    description: "Elegant pearl-embellished jewelry set with a sophisticated white and gold combination. Features artificial pearls set in gold-plated brass with delicate floral patterns. Perfect for weddings and formal events.",
    design: "DS-2407", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 170, originalPrice: 499, badge: "offer", costPrice: 85,
    weight: 32.4, metalType: "Gold", stoneType: "Pearl", stoneWeight: 1.5,
    makingCharge: 35, warranty: "3 months", sku: "SKU-BRA-007", quantityInStock: 22,
    isActive: true, isFeatured: false, brand: "brado jewellery", modelNo: "MOD-BRA-2407",
    baseMaterial: "Brass", plating: "Gold-plated", color: "White",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "KEYMAX Alloy Gold-plated Emerald Green Earring & Necklace Set",
    description: "Stunning emerald green and gold combination jewelry set. Features a layered necklace with emerald-colored stone accents and matching drop earrings. Modern design that complements both traditional and contemporary outfits.",
    design: "DS-2408", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 405, originalPrice: 999, badge: "price_dropped", costPrice: 202,
    weight: 42.8, metalType: "Gold", stoneType: "Emerald", stoneWeight: 3.5,
    makingCharge: 80, warranty: "1 year", sku: "SKU-KEY-008", quantityInStock: 12,
    isActive: true, isFeatured: false, brand: "KEYMAX", modelNo: "MOD-KEY-2408",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Green",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "TheSanga Brass Gold-plated Pink Rose Gold Jewel Set",
    description: "Rose gold finished jewelry set with a beautiful pink hue. Features intricate floral motifs and delicate detailing throughout. Lightweight construction ensures maximum comfort. Includes necklace, earrings, and bracelet.",
    design: "DS-2409", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 153, originalPrice: 999, badge: "offer", costPrice: 76,
    weight: 36.0, metalType: "Rose Gold", stoneType: "Cubic Zirconia", stoneWeight: 2.0,
    makingCharge: 40, warranty: "6 months", sku: "SKU-THE-009", quantityInStock: 28,
    isActive: true, isFeatured: true, brand: "TheSanga", modelNo: "MOD-THE-2409",
    baseMaterial: "Brass", plating: "Rose Gold-plated", color: "Pink",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Engagement",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "BRILLIANT BEADS JEWELS Alloy White Crystal Earring Set",
    description: "Crystalline white jewelry set that sparkles with every movement. Made from high-quality alloy with a rhodium-plated finish for extra shine. Features beautiful crystal stone work in a modern floral design.",
    design: "DS-2410", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 167, originalPrice: 599, badge: "offer", costPrice: 83,
    weight: 22.4, metalType: "Silver", stoneType: "Cubic Zirconia", stoneWeight: 3.0,
    makingCharge: 35, warranty: "3 months", sku: "SKU-BRI-010", quantityInStock: 35,
    isActive: true, isFeatured: false, brand: "BRILLIANT BEADS JEWELS", modelNo: "MOD-BRI-2410",
    baseMaterial: "Alloy", plating: "Rhodium", color: "White",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Everyday",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "OmKrishiv Brass Gold-plated Traditional Gold Bangles Set",
    description: "Traditional gold bangles set with intricate engravings. Each bangle is crafted from premium brass with a thick gold-plated finish. Set of 6 bangles with adjustable sizing. Perfect for festive wear.",
    design: "DS-2411", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 256, originalPrice: 999, badge: "price_dropped", costPrice: 128,
    weight: 85.6, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 55, warranty: "6 months", sku: "SKU-OMK-011", quantityInStock: 15,
    isActive: true, isFeatured: false, brand: "OmKrishiv", modelNo: "MOD-OMK-2411",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Bangles", idealFor: "Women", netQuantity: 6, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Shree Ju Stylish Rice Seed Design Multi Chain For Men Women",
    description: "Versatile multi-chain design with a unique rice seed pattern. Can be worn by both men and women. Features a sturdy lobster clasp and adjustable length. Great as a layered necklace or standalone piece.",
    design: "DS-2412", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 108, originalPrice: 799, badge: "offer", costPrice: 54,
    weight: 18.5, metalType: "Silver", stoneType: "None", stoneWeight: 0,
    makingCharge: 20, warranty: "No warranty", sku: "SKU-SHR-012", quantityInStock: 50,
    isActive: true, isFeatured: false, brand: "Shree Ju", modelNo: "MOD-SHR-2412",
    baseMaterial: "Brass", plating: "Silver-plated", color: "Silver",
    productType: "Chain", idealFor: "Unisex", netQuantity: 1, occasion: "Everyday",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "evashoppy Brass Gold-plated Designer Pendant Set",
    description: "Elegant pendant set with a large central pendant featuring intricate meenakari work. Comes with a matching chain and earrings. The gold-plated brass construction gives it a premium look at an affordable price.",
    design: "DS-2413", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 162, originalPrice: 999, badge: "offer", costPrice: 81,
    weight: 28.6, metalType: "Gold", stoneType: "Cubic Zirconia", stoneWeight: 2.0,
    makingCharge: 35, warranty: "3 months", sku: "SKU-EVA-013", quantityInStock: 20,
    isActive: true, isFeatured: false, brand: "evashoppy", modelNo: "MOD-EVA-2413",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Pendant Set", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "AVR JEWELS Alloy Gold-plated Pink Floral Earring Set",
    description: "Beautiful pink floral earring set crafted from lightweight alloy with gold plating. The flower-shaped design features pink enamel work with tiny crystal accents in the center. Comfortable for long wear.",
    design: "DS-2414", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 148, originalPrice: 999, badge: "offer", costPrice: 74,
    weight: 15.2, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 25, warranty: "3 months", sku: "SKU-AVR-014", quantityInStock: 32,
    isActive: true, isFeatured: true, brand: "AVR JEWELS", modelNo: "MOD-AVR-2414",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Pink",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Dailywear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "MAME CREATION High Quality Gold Plated 20 Inch Chain",
    description: "Premium 20-inch gold-plated chain with a sleek diamond-cut finish. Features a secure spring ring clasp and uniform link design. Perfect for men and women who prefer minimalist accessories.",
    design: "DS-2415", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 203, originalPrice: 999, badge: "offer", costPrice: 101,
    weight: 24.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 30, warranty: "6 months", sku: "SKU-MAM-015", quantityInStock: 45,
    isActive: true, isFeatured: false, brand: "MAME CREATION", modelNo: "MOD-MAM-2415",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Chain", idealFor: "Unisex", netQuantity: 1, occasion: "Everyday",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "KONASA Brass Gold-plated Green Emerald Stud Earrings",
    description: "Stunning emerald green stud earrings set in a gold-plated brass base. The gemstone-cut glass stones catch light beautifully. Classic round shape with secure screw-back posts.",
    design: "DS-2416", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 219, originalPrice: 1699, badge: "price_dropped", costPrice: 109,
    weight: 12.8, metalType: "Gold", stoneType: "Emerald", stoneWeight: 1.5,
    makingCharge: 40, warranty: "1 year", sku: "SKU-KON-016", quantityInStock: 25,
    isActive: true, isFeatured: false, brand: "KONASA", modelNo: "MOD-KON-2416",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Green",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Workwear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "ZENEME Brass Green Handcrafted Jewel Set",
    description: "Handcrafted jewelry set with a unique green patina finish. The antique-style brass construction gives it a vintage appeal. Features tribal-inspired motifs and a matching pair of earrings.",
    design: "DS-2417", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 301, originalPrice: 1899, badge: "offer", costPrice: 150,
    weight: 55.2, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 65, warranty: "6 months", sku: "SKU-ZEN-017", quantityInStock: 10,
    isActive: true, isFeatured: true, brand: "ZENEME", modelNo: "MOD-ZEN-2417",
    baseMaterial: "Brass", plating: "Matte", color: "Green",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Soumi store Alloy Gold-plated Gold Traditional Necklace",
    description: "Heavy traditional necklace with layered strands and a large central pendant. Made from durable alloy with radiant gold plating. Features temple jewellery-inspired design elements with hanging Kalis.",
    design: "DS-2418", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 383, originalPrice: 999, badge: "offer", costPrice: 191,
    weight: 62.4, metalType: "Gold", stoneType: "Ruby", stoneWeight: 2.5,
    makingCharge: 75, warranty: "1 year", sku: "SKU-SOU-018", quantityInStock: 8,
    isActive: true, isFeatured: false, brand: "Soumi store", modelNo: "MOD-SOU-2418",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Gold",
    productType: "Necklace", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "RARE ONE STUDIO Stainless Steel Gold-plated Matte Bracelet",
    description: "Modern matte-finish bracelet crafted from premium stainless steel with a subtle gold plating. Features a sleek minimalist design with an adjustable sliding knot. Perfect for daily wear and layering.",
    design: "DS-2419", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 232, originalPrice: 1199, badge: "price_dropped", costPrice: 116,
    weight: 20.5, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 30, warranty: "6 months", sku: "SKU-RAR-019", quantityInStock: 30,
    isActive: true, isFeatured: false, brand: "RARE ONE STUDIO", modelNo: "MOD-RAR-2419",
    baseMaterial: "Stainless Steel", plating: "Gold-plated", color: "Gold",
    productType: "Bracelet", idealFor: "Unisex", netQuantity: 1, occasion: "Dailywear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Divine rudras Mahakal Locket with Rudraksha Mala",
    description: "Spiritual Rudraksha mala with a brass Mahakal (Lord Shiva) pendant. Features 108+1 Rudraksha beads with a silk tassel. The pendant showcases intricate detailing of Lord Shiva's face.",
    design: "DS-2420", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 153, originalPrice: 1968, badge: "offer", costPrice: 76,
    weight: 42.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 25, warranty: "No warranty", sku: "SKU-DIV-020", quantityInStock: 20,
    isActive: true, isFeatured: false, brand: "Divine rudras", modelNo: "MOD-DIV-2420",
    baseMaterial: "Brass", plating: "Matte", color: "Brown",
    productType: "Pendant Set", idealFor: "Men", netQuantity: 1, occasion: "Everyday",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Vivanta Alloy Silver-plated White Crystal Drop Earrings",
    description: "Elegant drop earrings with sparkling crystal stones set in a silver-plated alloy base. The teardrop design catches light from every angle. Lightweight with comfortable French hook closures.",
    design: "DS-2421", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 180, originalPrice: 999, badge: "offer", costPrice: 90,
    weight: 14.6, metalType: "Silver", stoneType: "Cubic Zirconia", stoneWeight: 1.0,
    makingCharge: 30, warranty: "3 months", sku: "SKU-VIV-021", quantityInStock: 35,
    isActive: true, isFeatured: false, brand: "Vivanta", modelNo: "MOD-VIV-2421",
    baseMaterial: "Alloy", plating: "Silver-plated", color: "White",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Workwear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "TAGADO Copper Gold-plated Antique Finish Bracelet Set",
    description: "Set of 4 antique-finish copper bangles with intricate etching and gold overlay. Each bangle has a different traditional motif. The adjustable open design fits most wrist sizes comfortably.",
    design: "DS-2422", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 145, originalPrice: 650, badge: "offer", costPrice: 72,
    weight: 68.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 28, warranty: "No warranty", sku: "SKU-TAG-022", quantityInStock: 18,
    isActive: true, isFeatured: false, brand: "TAGADO", modelNo: "MOD-TAG-2422",
    baseMaterial: "Copper", plating: "Antique", color: "Gold",
    productType: "Bracelet", idealFor: "Women", netQuantity: 4, occasion: "Everyday",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "OChori Alloy Gold-plated Blue Gemstone Ring Set",
    description: "Set of 5 stackable rings with blue gemstone accents on a gold-plated alloy band. Each ring features a different cut of blue stone — round, oval, emerald, princess, and marquise. Adjustable bands fit all finger sizes.",
    design: "DS-2423", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 126, originalPrice: 999, badge: "offer", costPrice: 63,
    weight: 8.5, metalType: "Gold", stoneType: "Cubic Zirconia", stoneWeight: 1.0,
    makingCharge: 20, warranty: "3 months", sku: "SKU-OCH-023", quantityInStock: 40,
    isActive: true, isFeatured: true, brand: "OChori", modelNo: "MOD-OCH-2423",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Blue",
    productType: "Ring", idealFor: "Women", netQuantity: 5, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "TONOLIKA JEWELLERY Plastic Gold-plated Lightweight Necklace",
    description: "Ultra-lightweight necklace perfect for extended wear. Made from high-quality plastic with a convincing gold-plated finish. Features a modern geometric pattern. Ideal for daily office wear.",
    design: "DS-2424", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 250, originalPrice: 2100, badge: "offer", costPrice: 125,
    weight: 12.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 15, warranty: "No warranty", sku: "SKU-TON-024", quantityInStock: 55,
    isActive: true, isFeatured: false, brand: "TONOLIKA JEWELLERY", modelNo: "MOD-TON-2424",
    baseMaterial: "Plastic", plating: "Gold-plated", color: "Gold",
    productType: "Necklace", idealFor: "Women", netQuantity: 1, occasion: "Dailywear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Vivanta Alloy Multicolor Beaded Jewel Set for Girls",
    description: "Colorful beaded jewelry set designed for young girls. Features vibrant multicolor beads arranged in fun patterns. Set includes a necklace, earrings, and a bracelet. Nickel-free and safe for sensitive skin.",
    design: "DS-2425", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 162, originalPrice: 1550, badge: "offer", costPrice: 81,
    weight: 20.0, metalType: "Silver", stoneType: "None", stoneWeight: 0,
    makingCharge: 20, warranty: "3 months", sku: "SKU-VIV-025", quantityInStock: 30,
    isActive: true, isFeatured: false, brand: "Vivanta", modelNo: "MOD-VIV-2425",
    baseMaterial: "Alloy", plating: "Silver-plated", color: "Multicolor",
    productType: "Jewel Set", idealFor: "Girls", netQuantity: 1, occasion: "Gift",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "RIENTA JWL Alloy Gold-plated Red & Gold Mangalsutra",
    description: "Traditional red and gold mangalsutra with a modern twist. Features a gold-plated pendant with red stone accents suspended on a silk cord with gold beads. Lightweight and comfortable for daily wear.",
    design: "DS-2426", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 153, originalPrice: 1199, badge: "offer", costPrice: 76,
    weight: 16.8, metalType: "Gold", stoneType: "Ruby", stoneWeight: 1.0,
    makingCharge: 30, warranty: "6 months", sku: "SKU-RIE-026", quantityInStock: 25,
    isActive: true, isFeatured: false, brand: "RIENTA JWL", modelNo: "MOD-RIE-2426",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Red",
    productType: "Mangalsutra Set", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "J B JEWELLS Alloy Rhodium Silver Plated Blue Topaz Ring",
    description: "Elegant solitaire ring featuring a large blue topaz-style stone in a rhodium-plated silver finish. The four-prong setting secures the stone while allowing maximum light exposure. Adjustable band.",
    design: "DS-2427", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 299, originalPrice: 1299, badge: "price_dropped", costPrice: 149,
    weight: 6.2, metalType: "Silver", stoneType: "Cubic Zirconia", stoneWeight: 2.0,
    makingCharge: 45, warranty: "1 year", sku: "SKU-JB-027", quantityInStock: 22,
    isActive: true, isFeatured: false, brand: "J B JEWELLS", modelNo: "MOD-JB-2427",
    baseMaterial: "Alloy", plating: "Rhodium", color: "Blue",
    productType: "Ring", idealFor: "Women", netQuantity: 1, occasion: "Engagement",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "TheSanga Brass Antique Gold Oxidised Earring Set",
    description: "Handcrafted oxidised earrings with an antique silver finish. Features traditional tribal motifs with tiny bell-shaped danglers. The brass construction gives them a substantial feel while remaining comfortable.",
    design: "DS-2428", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 185, originalPrice: 799, badge: "offer", costPrice: 92,
    weight: 18.4, metalType: "Silver", stoneType: "None", stoneWeight: 0,
    makingCharge: 35, warranty: "3 months", sku: "SKU-THE-028", quantityInStock: 16,
    isActive: true, isFeatured: false, brand: "TheSanga", modelNo: "MOD-THE-2428",
    baseMaterial: "Brass", plating: "Antique", color: "Silver",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "KEYMAX Stainless Steel Silver-plated Men's Chain Necklace",
    description: "Bold and sturdy chain necklace designed for men. Made from premium stainless steel with a bright silver finish. Features a heavy curb chain design with a robust lobster clasp. Hypoallergenic and tarnish-resistant.",
    design: "DS-2429", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 349, originalPrice: 1499, badge: "price_dropped", costPrice: 174,
    weight: 35.0, metalType: "Silver", stoneType: "None", stoneWeight: 0,
    makingCharge: 50, warranty: "1 year", sku: "SKU-KEY-029", quantityInStock: 20,
    isActive: true, isFeatured: true, brand: "KEYMAX", modelNo: "MOD-KEY-2429",
    baseMaterial: "Stainless Steel", plating: "Silver-plated", color: "Silver",
    productType: "Chain", idealFor: "Men", netQuantity: 1, occasion: "Gift",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "LoveGift Lord Shiva Trishul Necklace Brass Pendant",
    description: "Spiritual Trishul (trident) pendant necklace made from polished brass. Features intricate detailing of Lord Shiva's symbol with a rudraksha bead accent. Comes on a adjustable black cord. Unisex design.",
    design: "DS-2430", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 82, originalPrice: 260, badge: "offer", costPrice: 41,
    weight: 15.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 15, warranty: "No warranty", sku: "SKU-LOV-030", quantityInStock: 40,
    isActive: true, isFeatured: false, brand: "LoveGift", modelNo: "MOD-LOV-2430",
    baseMaterial: "Brass", plating: "Polished", color: "Gold",
    productType: "Pendant Set", idealFor: "Unisex", netQuantity: 1, occasion: "Everyday",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Vivanta Alloy Rose Gold-plated Pink Crystal Bracelet",
    description: "Delicate rose gold bracelet with pink crystal accents. The chain features alternating crystal and metal bead patterns. Adjustable length with a secure lobster clasp. Perfect for stacking or wearing alone.",
    design: "DS-2431", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 170, originalPrice: 1299, badge: "offer", costPrice: 85,
    weight: 10.5, metalType: "Rose Gold", stoneType: "Cubic Zirconia", stoneWeight: 0.5,
    makingCharge: 25, warranty: "3 months", sku: "SKU-VIV-031", quantityInStock: 35,
    isActive: true, isFeatured: false, brand: "Vivanta", modelNo: "MOD-VIV-2431",
    baseMaterial: "Alloy", plating: "Rose Gold-plated", color: "Pink",
    productType: "Bracelet", idealFor: "Women", netQuantity: 1, occasion: "Dailywear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Atasi International Alloy Gold-plated White Pearl Necklace Set",
    description: "Lustrous pearl necklace set with a classic white and gold combination. Features 8mm artificial pearls strung on a gold-plated chain with a decorative gold spacer pattern. Matching earrings included.",
    design: "DS-2432", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 347, originalPrice: 1999, badge: "offer", costPrice: 173,
    weight: 38.0, metalType: "Gold", stoneType: "Pearl", stoneWeight: 3.0,
    makingCharge: 60, warranty: "6 months", sku: "SKU-ATA-032", quantityInStock: 12,
    isActive: true, isFeatured: true, brand: "Atasi International", modelNo: "MOD-ATA-2432",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "White",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "brado jewellery Brass Gold-plated Peacock Inspired Earrings",
    description: "Stunning peacock-inspired earrings with intricate tail-feather detailing. Made from brass with rich gold plating and vibrant blue/green enamel work. Lightweight despite their impressive size.",
    design: "DS-2433", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 195, originalPrice: 699, badge: "offer", costPrice: 97,
    weight: 16.0, metalType: "Gold", stoneType: "Cubic Zirconia", stoneWeight: 1.0,
    makingCharge: 35, warranty: "3 months", sku: "SKU-BRA-033", quantityInStock: 14,
    isActive: true, isFeatured: false, brand: "brado jewellery", modelNo: "MOD-BRA-2433",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Multicolor",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "OmKrishiv Copper Silver-plated Antique Anklet Set",
    description: "Traditional silver-finish anklet set with tiny bell charms. Made from copper with a tarnish-resistant silver plating. Features adjustable length with a decorative hook closure. Set of 2 anklets.",
    design: "DS-2434", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 178, originalPrice: 899, badge: "offer", costPrice: 89,
    weight: 28.0, metalType: "Silver", stoneType: "None", stoneWeight: 0,
    makingCharge: 25, warranty: "3 months", sku: "SKU-OMK-034", quantityInStock: 20,
    isActive: true, isFeatured: false, brand: "OmKrishiv", modelNo: "MOD-OMK-2434",
    baseMaterial: "Copper", plating: "Silver-plated", color: "Silver",
    productType: "Anklet", idealFor: "Women", netQuantity: 2, occasion: "Everyday",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "ZENEME Alloy Matte Gold Geometric Statement Necklace",
    description: "Modern geometric statement necklace with clean lines and a matte gold finish. Made from lightweight alloy with a sophisticated matte gold plating. The asymmetrical design is perfect for contemporary fashion lovers.",
    design: "DS-2435", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 275, originalPrice: 1599, badge: "offer", costPrice: 137,
    weight: 30.5, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 55, warranty: "6 months", sku: "SKU-ZEN-035", quantityInStock: 15,
    isActive: true, isFeatured: true, brand: "ZENEME", modelNo: "MOD-ZEN-2435",
    baseMaterial: "Alloy", plating: "Matte", color: "Gold",
    productType: "Necklace", idealFor: "Women", netQuantity: 1, occasion: "Workwear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "AVR JEWELS Alloy Silver-plated Purple Amethyst Earring Set",
    description: "Elegant purple amethyst-colored earring set with a silver-plated finish. Features a cluster of small stones arranged in a floral pattern. Lightweight with comfortable push-back posts for pierced ears.",
    design: "DS-2436", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 165, originalPrice: 899, badge: "offer", costPrice: 82,
    weight: 12.0, metalType: "Silver", stoneType: "Cubic Zirconia", stoneWeight: 1.5,
    makingCharge: 25, warranty: "3 months", sku: "SKU-AVR-036", quantityInStock: 28,
    isActive: true, isFeatured: false, brand: "AVR JEWELS", modelNo: "MOD-AVR-2436",
    baseMaterial: "Alloy", plating: "Silver-plated", color: "Purple",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Soumi store Alloy Gold-plated Red Ruby Choker Necklace",
    description: "Traditional choker-style necklace featuring rich red ruby-colored stones set in a gold-plated alloy base. The wide choker design sits elegantly on the neck. Features intricate stonework with a central emerald accent.",
    design: "DS-2437", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 420, originalPrice: 1899, badge: "price_dropped", costPrice: 210,
    weight: 48.0, metalType: "Gold", stoneType: "Ruby", stoneWeight: 5.0,
    makingCharge: 85, warranty: "1 year", sku: "SKU-SOU-037", quantityInStock: 8,
    isActive: true, isFeatured: false, brand: "Soumi store", modelNo: "MOD-SOU-2437",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Red",
    productType: "Necklace", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "MAME CREATION Alloy Gold-plated Men's Cufflinks Set",
    description: "Sophisticated cufflink set for men featuring a classic round design with a subtle gold finish. Made from alloy with durable gold plating. The bullet-back closure ensures a secure fit. Comes in a gift box.",
    design: "DS-2438", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 315, originalPrice: 1299, badge: "offer", costPrice: 157,
    weight: 8.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 40, warranty: "6 months", sku: "SKU-MAM-038", quantityInStock: 18,
    isActive: true, isFeatured: false, brand: "MAME CREATION", modelNo: "MOD-MAM-2438",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "Gold",
    productType: "Cufflinks", idealFor: "Men", netQuantity: 1, occasion: "Workwear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "KONASA Copper Antique Silver Tribal Earring Collection",
    description: "Bold tribal-style earrings with an antique silver finish. Handcrafted from copper with intricate tribal patterns etched into the surface. Features a combination of geometric shapes and hanging elements.",
    design: "DS-2439", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 238, originalPrice: 1299, badge: "offer", costPrice: 119,
    weight: 22.5, metalType: "Silver", stoneType: "None", stoneWeight: 0,
    makingCharge: 35, warranty: "3 months", sku: "SKU-KON-039", quantityInStock: 12,
    isActive: true, isFeatured: false, brand: "KONASA", modelNo: "MOD-KON-2439",
    baseMaterial: "Copper", plating: "Antique", color: "Silver",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "RARE ONE STUDIO Brass Matte Gold Layered Necklace Set",
    description: "Trendy layered necklace set with three independent chains of varying lengths. Each chain has a unique pendant — a geometric disc, a bar, and a coin. Matte gold finish gives it a modern aesthetic.",
    design: "DS-2440", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 289, originalPrice: 1499, badge: "price_dropped", costPrice: 144,
    weight: 26.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 45, warranty: "6 months", sku: "SKU-RAR-040", quantityInStock: 14,
    isActive: true, isFeatured: true, brand: "RARE ONE STUDIO", modelNo: "MOD-RAR-2440",
    baseMaterial: "Brass", plating: "Matte", color: "Gold",
    productType: "Necklace", idealFor: "Women", netQuantity: 1, occasion: "Workwear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Divine rudras Brass Gold-plated Om Pendant with Chain",
    description: "Sacred Om symbol pendant made from polished brass with a radiant gold finish. The pendant features the Om symbol engraved on both sides with a decorative border. Comes with a matching gold-plated chain.",
    design: "DS-2441", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 95, originalPrice: 499, badge: "offer", costPrice: 47,
    weight: 12.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 18, warranty: "No warranty", sku: "SKU-DIV-041", quantityInStock: 45,
    isActive: true, isFeatured: false, brand: "Divine rudras", modelNo: "MOD-DIV-2441",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Pendant Set", idealFor: "Unisex", netQuantity: 1, occasion: "Everyday",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Atasi International Alloy Rhodium Pink & Silver Jewel Set",
    description: "Contemporary pink and silver jewelry set with a rhodium-plated finish. Features rose-pink enamel work with silver accents. Set includes a necklace, earrings, and a dainty bracelet. Modern styling for the fashion-forward woman.",
    design: "DS-2442", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 324, originalPrice: 1999, badge: "offer", costPrice: 162,
    weight: 34.0, metalType: "Silver", stoneType: "None", stoneWeight: 0,
    makingCharge: 55, warranty: "6 months", sku: "SKU-ATA-042", quantityInStock: 10,
    isActive: true, isFeatured: false, brand: "Atasi International", modelNo: "MOD-ATA-2442",
    baseMaterial: "Alloy", plating: "Rhodium", color: "Pink",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Engagement",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "Shree Ju Brass Gold-plated Festive Anklet with Bells",
    description: "Traditional anklet with charming golden bells that create a gentle tinkling sound when walking. Made from sturdy brass with a bright gold finish. Adjustable chain length with a safe hook closure.",
    design: "DS-2443", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 135, originalPrice: 699, badge: "offer", costPrice: 67,
    weight: 32.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 22, warranty: "3 months", sku: "SKU-SHR-043", quantityInStock: 22,
    isActive: true, isFeatured: false, brand: "Shree Ju", modelNo: "MOD-SHR-2443",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Anklet", idealFor: "Women", netQuantity: 1, occasion: "Festive",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "BRILLIANT BEADS JEWELS Alloy Gold-plated Pearl Drop Earrings",
    description: "Graceful pearl drop earrings with a gold-plated alloy setting. Each earring features a lustrous artificial pearl suspended from a decorative gold cap. Classic design that works for both casual and formal occasions.",
    design: "DS-2444", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 125, originalPrice: 599, badge: "offer", costPrice: 62,
    weight: 8.5, metalType: "Gold", stoneType: "Pearl", stoneWeight: 1.0,
    makingCharge: 20, warranty: "3 months", sku: "SKU-BRI-044", quantityInStock: 38,
    isActive: true, isFeatured: false, brand: "BRILLIANT BEADS JEWELS", modelNo: "MOD-BRI-2444",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "White",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Workwear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "evashoppy Alloy Gold-plated Layered Pearl & Crystal Necklace",
    description: "Elegant layered necklace combining pearls and clear crystals on a gold-plated chain. Two strands of varying lengths create a sophisticated layered look. The crystal accents add sparkle while pearls provide classic elegance.",
    design: "DS-2445", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 230, originalPrice: 1199, badge: "offer", costPrice: 115,
    weight: 28.0, metalType: "Gold", stoneType: "Pearl", stoneWeight: 2.0,
    makingCharge: 40, warranty: "6 months", sku: "SKU-EVA-045", quantityInStock: 16,
    isActive: true, isFeatured: false, brand: "evashoppy", modelNo: "MOD-EVA-2445",
    baseMaterial: "Alloy", plating: "Gold-plated", color: "White",
    productType: "Necklace", idealFor: "Women", netQuantity: 1, occasion: "Engagement",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "LoveGift Brass Gold-plated Heart Pendant Couple Set",
    description: "Romantic couple pendant set featuring two interlocking heart halves. Each pendant is made from polished brass with gold plating. One pendant says 'Love' and the other says 'You'. Comes on matching chains in a gift box.",
    design: "DS-2446", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 145, originalPrice: 799, badge: "offer", costPrice: 72,
    weight: 10.0, metalType: "Gold", stoneType: "None", stoneWeight: 0,
    makingCharge: 20, warranty: "No warranty", sku: "SKU-LOV-046", quantityInStock: 30,
    isActive: true, isFeatured: true, brand: "LoveGift", modelNo: "MOD-LOV-2446",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Pendant Set", idealFor: "Unisex", netQuantity: 2, occasion: "Gift",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "SYGA 5 Pieces Unicorn Fashion Jewelry Set for Girls",
    description: "Magical unicorn-themed jewelry set for young girls. Includes a rainbow necklace, unicorn horn ring, star earrings, a charm bracelet, and a glittery hair clip. Made from safe, nickel-free materials. Colorful and fun.",
    design: "DS-2447", images: [imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 254, originalPrice: 500, badge: "price_dropped", costPrice: 127,
    weight: 25.0, metalType: "Silver", stoneType: "Cubic Zirconia", stoneWeight: 0.5,
    makingCharge: 30, warranty: "3 months", sku: "SKU-SYG-047", quantityInStock: 25,
    isActive: true, isFeatured: false, brand: "SYGA", modelNo: "MOD-SYG-2447",
    baseMaterial: "Alloy", plating: "Silver-plated", color: "Multicolor",
    productType: "Jewel Set", idealFor: "Girls", netQuantity: 5, occasion: "Gift",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "KONASA Brass Gold-plated Black Onyx Men's Ring",
    description: "Bold men's ring featuring a genuine Onyx-style black stone set in a gold-plated brass band. The rectangular stone setting gives it a sophisticated look. Adjustable band fits most ring sizes.",
    design: "DS-2448", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 195, originalPrice: 999, badge: "offer", costPrice: 97,
    weight: 8.0, metalType: "Gold", stoneType: "Cubic Zirconia", stoneWeight: 0.5,
    makingCharge: 25, warranty: "6 months", sku: "SKU-KON-048", quantityInStock: 20,
    isActive: true, isFeatured: false, brand: "KONASA", modelNo: "MOD-KON-2448",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Black",
    productType: "Ring", idealFor: "Men", netQuantity: 1, occasion: "Party",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "brado jewellery Alloy Silver-plated Blue Sea Glass Earrings",
    description: "Ocean-inspired earrings featuring sea glass-blue stones set in a silver-plated alloy frame. The irregular stone shapes give each earring a unique, organic look. Lightweight with comfortable fish hook findings.",
    design: "DS-2449", images: [imgUrl(), imgUrl()],
    videoUrl: "", price: 155, originalPrice: 649, badge: "offer", costPrice: 77,
    weight: 11.0, metalType: "Silver", stoneType: "Cubic Zirconia", stoneWeight: 1.0,
    makingCharge: 28, warranty: "3 months", sku: "SKU-BRA-049", quantityInStock: 24,
    isActive: true, isFeatured: false, brand: "brado jewellery", modelNo: "MOD-BRA-2449",
    baseMaterial: "Alloy", plating: "Silver-plated", color: "Blue",
    productType: "Earrings", idealFor: "Women", netQuantity: 1, occasion: "Dailywear",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
  {
    name: "OChori Brass Gold-plated Temple Jewelry Set",
    description: "Exquisite temple jewelry set inspired by traditional South Indian designs. Features intricate depictions of deities and temple architecture. Made from premium brass with a thick gold plating. Set includes necklace, earrings, and waist belt.",
    design: "DS-2450", images: [imgUrl(), imgUrl(), imgUrl(), imgUrl()],
    videoUrl: "", price: 450, originalPrice: 2499, badge: "price_dropped", costPrice: 225,
    weight: 75.0, metalType: "Gold", stoneType: "Ruby", stoneWeight: 4.0,
    makingCharge: 95, warranty: "1 year", sku: "SKU-OCH-050", quantityInStock: 5,
    isActive: true, isFeatured: true, brand: "OChori", modelNo: "MOD-OCH-2450",
    baseMaterial: "Brass", plating: "Gold-plated", color: "Gold",
    productType: "Jewel Set", idealFor: "Women", netQuantity: 1, occasion: "Wedding",
    createdAt: Timestamp.fromDate(new Date()), updatedAt: Timestamp.fromDate(new Date()),
  },
];

export function generateDummyProducts(categoryId: string): DummyProduct[] {
  return products.map((p) => ({
    ...p,
    categoryId,
  }));
}
